### ISSUE TITLE
Doesn't work on arm64-v8a

### ISSUE THREAD

**Issue by mattmiley** [breekmd/SpatialiteForms#1]
I got this working on the Android emulators for 8.1 and marshmallow. It's just not working on my device pixel 3 xl. Any trouble shooting tips?

**Comment by breekmd** [comment]
are you using a prepackaged database?
also, which version are you using and please post any logs here as well.

**Comment by mattmiley** [comment]
I'm using your countrydata.db 
nuget :Version 0.0.3	

I'm just running your readme code..

```
var dbPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "countryData.db");
                SpatialiteConnection spatialite = CrossSpatialiteForms.Current.GetSpatialiteConnection(dbPath, "countryData.db", true);

                var info = spatialite.SpatialiteInfo;
                var region = spatialite.SQLiteConnection.Query<Region>("select name , AsText(Geometry) GeometryText, Geometry from region where within(Makepoint(-99.145539, 44.685479), geometry);").FirstOrDefault();
               
```

It breaks at var info = spatialite.SpatialiteInfo;
`Error: no such function: spatialite_version`

Then I commented out the line it breaks on : spatialite.SpatialiteInfo;  Then it says 
`Error: no such function: AsText
`
Seems like the spatialite part of sqlite isnt working at all since that's a spatial function.
Everything seems to work well on the emulators with android 8.1 and lower.

I'm not really sure how to look for the issue, this is my first time using a native library in xamarin.

**Comment by breekmd** [comment]
i've reasearched and it appears an issue with Android 9
i'll try and push a fix for that

**Comment by mattmiley** [comment]
Awesome, I'll report my findings. Thanks!!

**Comment by mattmiley** [comment]
Is it possible to get a arm64-v8a build of libspatialite.so? I think that's what i need to get this library to work on arm64-v8a.

**Comment by breekmd** [comment]
the provided build of libspatialite.so should work on arm64-v8a as well.
the issue on Android 9.0 is coming from .wal files (see https://source.android.com/devices/tech/perf/compatibility-wal)

**Comment by mattmiley** [comment]
Can we just disable wal with that bool example in your link?

**Comment by breekmd** [comment]
please try the new version and let me know if it works

**Comment by mattmiley** [comment]
It still shows the same error. It only works if I target armeabi-v7a on my build. I'd really like to have it on arm64, so I tried creating a libs/arm64-v8a folder and put the arm32 .so in there and it will atleast show up in this Native Libs Monitor App i downloaded (see image), but it still doesn't recognize the .SpatialiteInfo property. Where did you get this libspatialite.so file from? I feel like it needs to be compiled for arm64 in order for it to work. In the readme, you say 

> will also run on arm64-v8a

How do you know that it will and wouldnt you need the arm64-v8a folder in the libs folder in order for that to work?

![Screenshot_20190331-002014](https://user-images.githubusercontent.com/6834180/55284849-bde48200-534c-11e9-99b8-cf567775fc02.png)

**Comment by breekmd** [comment]
if you target arm64-v8a specifically, then it would not work. however targeting armeabi-v7a then it will run on any arm64 device as well. any reason you're specifically targeting arm64-v8a, is there a performance bottleneck when targeting armeabi-v7a?

to obtain the .so file you have to build the source code of spatialite, targeting android specifically and by writing a .ac & .mk file. you have to make sure you get the correct versions of the components required by spatialite to build (i.e. libiconv, geos, proj etc..) this is not very straightforward and does take some time, unless you've done it before and have everything at hand.

**Comment by mattmiley** [comment]
I previously had all my libs on arm64, so I wanted the performance benefits of arm64 within my app. Thanks for this easily usable nuget/project!

**Comment by mattmiley** [comment]
Hey @breekmd It looks like everyone will need the arm-64-v8a version to publish anything in the play store starting Aug 1st 2019. [Ensure that your app supports 64-bit devices](https://developer.android.com/distribute/best-practices/develop/64-bit)  Is there any change you can build this and share the file in this repo? I imagine lots of people will need it in the future.

**Comment by breekmd** [comment]
hey @mattmiley I will look into that. I am currently very busy at work, however am aiming to release the v8a 64 bit version before 1st Aug 2019. (hopefully sooner)

**Comment by hajmajeboss** [comment]
Hello, are you going to release the v8a version before Aug 2019? Thank you for your reply.

**Comment by breekmd** [comment]
@hajmajeboss v8a was pushed now.
please check if any issues and let me know.
