### ISSUE TITLE
Need v8a 64 bit version for android

### ISSUE THREAD

**Issue by mattmiley** [breekmd/SpatialiteForms#2]
Sorry, but I can't publish to Google play without an v8a 64 bit version of this library. [docs](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)

**Comment by breekmd** [comment]
just pushed the 64 bit version for Android.

let me know if any issues.

**Comment by mattmiley** [comment]
Wow thanks!! Can’t wait to test!! 😀

**Comment by breekmd** [comment]
doesn't seem to be related, unless I'm missing something?

**Comment by breekmd** [comment]
i've tested on a emulator, not a real device and it worked fine.

**Comment by mattmiley** [comment]
Are you sure you compiled an arm64 APK? Project properties -> Advanced -> Supported Architectures

Also the emulator was arm64 correct?

**Comment by mattmiley** [comment]
Never mind, I got it working. I confirmed its working correctly with arm-64. Not sure what the issue was before. I uninstalled and reinstalled a couple of times. Thanks so much for this!!
